#! /bin/sh

FILE="out"

getdata() {
	cat "${FILE}"
#		| grep '^2015-12-05'
}

simlatebb() {
	while read LINE ; do
		echo "${LINE}"
		sleep 0.5
	done
}

main() {
	getdata \
		| simlatebb \
		| ./bbcl
}

main
